#!/usr/bin/env python

import os
import glob
import sys
import zipfile

try:
    import zlib
    compression = zipfile.ZIP_DEFLATED
except:
    compression = zipfile.ZIP_STORED


MAIN_PY_CONTENT = """\
#!/usr/bin/env python
import pip
import sys
sys.exit(pip.main())
"""

def main():
    file_name = 'pipx'
    root_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
    os.chdir(root_dir)
    try:
        main_py = open('__main__.py', 'w')
        main_py.write(MAIN_PY_CONTENT)
        main_py.close()
        zf = zipfile.PyZipFile(file_name, mode='w', compression=compression)
        try:
            zf.debug = 4
            for package in ['pip', '__main__.py']:
                zf.writepy(package)
        finally:
            zf.close()
        pip_zip = open(file_name, 'r')
        content = pip_zip.read()
        pip_zip.close()

        pip_zip = open(file_name, 'w')
        pip_zip.write("#!/usr/bin/env python\n"+content)
        pip_zip.close()

        if hasattr(os, 'chmod'):
            oldmode = os.stat(file_name).st_mode & 07777
            newmode = (oldmode | 0555) & 07777
            os.chmod(file_name, newmode)
            print 'Made resulting file executable. Use it as `./%s`.' % file_name
    finally:
        for path in glob.glob('__main__.py*'):
            os.remove(path)

if __name__ == '__main__':
    main()
