#!/usr/bin/env python

import os
import sys
from packager import generate_script

here = os.path.dirname(os.path.abspath(__file__))
file_name = os.path.join(here, 'install-pip.py')

def main():
    sys.stdout.write("Creating pip bootstrapper...")
    script = generate_script(
        entry='import pip; pip.bootstrap()',
        packages=['pip'],
    )
    with open(file_name, 'w') as f:
        f.write(script)
    sys.stdout.write('done.\n')
    if hasattr(os, 'chmod'):
        oldmode = os.stat(file_name).st_mode & 07777
        newmode = (oldmode | 0555) & 07777
        os.chmod(file_name, newmode)
        sys.stdout.write('Made resulting file %s executable.\n\n' % file_name)

if __name__ == '__main__':
    main()
