#!/bin/sh

FILE="${0#./}"
DIR="${FILE%/*}"
CWD=$(pwd)

cd $DIR/..

CMD="$1"
if [ "$CMD" = "release" ] ; then
  python -c 'import setuptools; __file__="setup.py"; execfile(__file__)' register sdist upload
  CMD="publish"
fi

mkdir -p docs/_static docs/_build
sphinx-build -E -b html docs/ docs/_build || exit 1
if [ "$CMD" = "publish" ] ; then
  cd docs/_build/
  echo "Uploading files..."
  scp -r * root@cloudsilverlining.org:/var/lib/silverlining/writable-roots/bbdocs/pip.openplans.org/
  ssh root@cloudsilverlining.org 'chown -R www-data:www-data /var/lib/silverlining/writable-roots/bbdocs/'
fi

cd $CWD
