---
name: Bug report
about: Something is not working correctly.
title: ""
labels: "S: needs triage, type: bug"
issue_body: true  # default: true, adds a classic WSYWIG textarea, if on
body:
- type: markdown
  attributes:
    value: |
      ⚠
      If you're reporting an issue for `--use-feature=2020-resolver`,
      use the "Dependency resolver failures / errors" template instead.
- type: markdown
  attributes:
    value: "**Environment**"
- type: input
  attributes:
    label: pip version
  validations:
    required: true
- type: input
  attributes:
    label: Python version
  validations:
    required: true
- type: input
  attributes:
    label: OS
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional information
    description: >-
      Feel free to add more information about your environment here.

- type: textarea
  attributes:
    label: Description
    description: >-
      A clear and concise description of what the bug is.

- type: textarea
  attributes:
    label: Expected behavior
    description: >-
      A clear and concise description of what you expected to happen.

- type: textarea
  attributes:
    label: How to Reproduce
    description: >-
      Describe the steps to reproduce this bug.
    value: |
      1. Get package from '...'
      2. Then run '...'
      3. An error occurs.

- type: textarea
  attributes:
    label: Output
    description: >-
      Paste the output of the steps above, including the commands
      themselves and pip's output/traceback etc.
    value: |
      ```console

      ```

- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [PSF Code of Conduct][CoC] first.

      [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
    options:
    - label: I agree to follow the PSF Code of Conduct
      required: true
...
