lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "build"
version = "1.5.0"

[[packages.wheels]]
name = "build-1.5.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/0d/fe/6bea5c9162869c5beba5d9c8abbed835ec85bf1ec1fba05a3822325c45f3/build-1.5.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "13f3eecb844759ab66efec90ca17639bbf14dc06cb2fdf37a9010322d9c50a6f"

[[packages]]
name = "flit-core"
version = "4.0.2"

[[packages.wheels]]
name = "flit_core-4.0.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/40/79/099ca4ec8c22b6462577ef933f90eed4c47cdcf6473d2cfcad275c3ce232/flit_core-4.0.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "8d80717e28d982b41594ed5b14d4e89fbc5bad55473fde27994a3101db18a94e"

[[packages]]
name = "packaging"
version = "26.3"

[[packages.wheels]]
name = "packaging-26.3-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/63/34/ba1c580383c9eada3711951fef0795c80b829a078d72188184bcab9dd527/packaging-26.3-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "d7193f7c8e4e93f444fde0262bf90af30e16fa0ad0ad44cb553c87339b23cd1c"

[[packages]]
name = "pyproject-hooks"
version = "1.2.0"

[[packages.wheels]]
name = "pyproject_hooks-1.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/bd/24/12818598c362d7f300f18e74db45963dbcb85150324092410c8b49405e42/pyproject_hooks-1.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9e5c6bfa8dcc30091c74b0cf803c81fdd29d94f01992a7707bc97babb1141913"
