from __future__ import annotations

import os
import sys
from collections.abc import Iterable, Iterator
from importlib.util import cache_from_source
from pathlib import Path
from unittest.mock import Mock

import pytest

import pip._internal.req.req_uninstall
from pip._internal.req.req_uninstall import (
    PathCompactor,
    StashedUninstallPathSet,
    UninstallPathSet,
    UninstallPthEntries,
    compact,
    compress_for_output_listing,
    compress_for_rename,
    uninstallation_paths,
)

from tests.lib.filesystem import create_file


# Pretend all files are local, so UninstallPathSet accepts files in the tmpdir,
# outside the virtualenv
def mock_permitted(ups: UninstallPathSet, path: str) -> bool:
    return True


def test_uninstallation_paths() -> None:
    class dist:
        def iter_declared_entries(self) -> Iterator[str] | None:
            return iter(["file.py", "file.pyc", "file.so", "nopyc.py"])

        location = ""

    d = dist()

    paths = list(uninstallation_paths(d))

    expected = [
        "file.py",
        "file.pyc",
        "file.pyo",
        "file.so",
        "nopyc.py",
        "nopyc.pyc",
        "nopyc.pyo",
    ]

    assert paths == expected

    # Avoid an easy 'unique generator' bug
    paths2 = list(uninstallation_paths(d))

    assert paths2 == paths


def test_compressed_listing(tmpdir: Path) -> None:
    def in_tmpdir(paths: list[str]) -> list[str]:
        return [
            str(os.path.join(tmpdir, path.replace("/", os.path.sep))) for path in paths
        ]

    sample = in_tmpdir(
        [
            "lib/mypkg.dist-info/METADATA",
            "lib/mypkg.dist-info/PKG-INFO",
            "lib/mypkg/would_be_removed.txt",
            "lib/mypkg/would_be_skipped.skip.txt",
            "lib/mypkg/__init__.py",
            "lib/mypkg/my_awesome_code.py",
            "lib/mypkg/__pycache__/my_awesome_code-magic.pyc",
            "lib/mypkg/support/support_file.py",
            "lib/mypkg/support/more_support.py",
            "lib/mypkg/support/would_be_skipped.skip.py",
            "lib/mypkg/support/__pycache__/support_file-magic.pyc",
            "lib/random_other_place/file_without_a_dot_pyc",
            "bin/mybin",
        ]
    )

    # Create the required files
    for fname in sample:
        create_file(fname, "random blub")

    # Remove the files to be skipped from the paths
    sample = [path for path in sample if ".skip." not in path]

    expected_remove = in_tmpdir(
        [
            "bin/mybin",
            "lib/mypkg.dist-info/*",
            "lib/mypkg/*",
            "lib/random_other_place/file_without_a_dot_pyc",
        ]
    )

    expected_skip = in_tmpdir(
        [
            "lib/mypkg/would_be_skipped.skip.txt",
            "lib/mypkg/support/would_be_skipped.skip.py",
        ]
    )

    expected_rename = in_tmpdir(
        [
            "bin/",
            "lib/mypkg.dist-info/",
            "lib/mypkg/would_be_removed.txt",
            "lib/mypkg/__init__.py",
            "lib/mypkg/my_awesome_code.py",
            "lib/mypkg/__pycache__/",
            "lib/mypkg/support/support_file.py",
            "lib/mypkg/support/more_support.py",
            "lib/mypkg/support/__pycache__/",
            "lib/random_other_place/",
        ]
    )

    will_remove, will_skip = compress_for_output_listing(sample)
    will_rename = compress_for_rename(sample)
    assert sorted(expected_skip) == sorted(compact(will_skip))
    assert sorted(expected_remove) == sorted(compact(will_remove))
    assert sorted(expected_rename) == sorted(compact(will_rename))


def test_compact_keeps_minimal_parent_paths(tmpdir: Path) -> None:
    parent = os.path.join(tmpdir, "pkg")
    nested = os.path.join(parent, "module.py")
    deeper = os.path.join(parent, "subpkg", "module.py")
    sibling = os.path.join(tmpdir, "pkg-extra", "module.py")

    assert compact([nested, deeper, sibling, parent]) == {parent, sibling}


def test_compact_keeps_literal_trailing_star_paths(tmpdir: Path) -> None:
    # A trailing star is only special for display wildcards generated by pip.
    # A real POSIX filename ending with "*" must still be kept.
    plain = os.path.join(tmpdir, "pkg")
    star = os.path.join(tmpdir, "pkg*")

    assert compact([plain, star]) == {plain, star}


class TestUninstallPathSet:
    def test_add(self, tmpdir: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(
            pip._internal.req.req_uninstall.UninstallPathSet,
            "_permitted",
            mock_permitted,
        )
        # Fix case for windows tests
        file_extant = os.path.normcase(os.path.join(tmpdir, "foo"))
        file_nonexistent = os.path.normcase(os.path.join(tmpdir, "nonexistent"))
        with open(file_extant, "w"):
            pass

        ups = UninstallPathSet(dist=Mock())
        assert ups._paths == set()
        ups.add(file_extant)
        assert ups._paths == {file_extant}

        ups.add(file_nonexistent)
        assert ups._paths == {file_extant}

    def test_add_pth(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(
            pip._internal.req.req_uninstall.UninstallPathSet,
            "_permitted",
            mock_permitted,
        )
        # Fix case for windows tests
        tmpdir = os.path.normcase(tmp_path)
        on_windows = sys.platform == "win32"
        pth_file = os.path.join(tmpdir, "foo.pth")
        relative = "../../example"
        if on_windows:
            share = "\\\\example\\share\\"
            share_com = "\\\\example.com\\share\\"
        # Create a .pth file for testing
        with open(pth_file, "w") as f:
            f.writelines([tmpdir, "\n", relative, "\n"])
            if on_windows:
                f.writelines([share, "\n", share_com, "\n"])
        # Add paths to be removed
        pth = UninstallPthEntries(pth_file)
        pth.add(tmpdir)
        pth.add(relative)
        if on_windows:
            pth.add(share)
            pth.add(share_com)
        # Check that the paths were added to entries
        if on_windows:
            check = {tmpdir, relative, share, share_com}
        else:
            check = {tmpdir, relative}
        assert pth.entries == check

    @pytest.mark.skipif("sys.platform == 'win32'")
    def test_add_symlink(self, tmpdir: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(
            pip._internal.req.req_uninstall.UninstallPathSet,
            "_permitted",
            mock_permitted,
        )
        f = os.path.join(tmpdir, "foo")
        with open(f, "w"):
            pass
        foo_link = os.path.join(tmpdir, "foo_link")
        os.symlink(f, foo_link)

        ups = UninstallPathSet(dist=Mock())
        ups.add(foo_link)
        assert ups._paths == {foo_link}

    def test_compact_shorter_path(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(
            pip._internal.req.req_uninstall.UninstallPathSet,
            "_permitted",
            mock_permitted,
        )
        monkeypatch.setattr("os.path.exists", lambda p: True)
        # This deals with nt/posix path differences
        short_path = os.path.normcase(
            os.path.abspath(os.path.join(os.path.sep, "path"))
        )
        ups = UninstallPathSet(dist=Mock())
        ups.add(short_path)
        ups.add(os.path.join(short_path, "longer"))
        assert compact(ups._paths) == {short_path}

    @pytest.mark.skipif("sys.platform == 'win32'")
    def test_detect_symlink_dirs(
        self, monkeypatch: pytest.MonkeyPatch, tmpdir: Path
    ) -> None:
        monkeypatch.setattr(
            pip._internal.req.req_uninstall.UninstallPathSet,
            "_permitted",
            mock_permitted,
        )

        # construct 2 paths:
        #  tmpdir/dir/file
        #  tmpdir/dirlink/file (where dirlink is a link to dir)
        d = tmpdir.joinpath("dir")
        d.mkdir()
        dlink = tmpdir.joinpath("dirlink")
        os.symlink(d, dlink)
        d.joinpath("file").touch()
        path1 = str(d.joinpath("file"))
        path2 = str(dlink.joinpath("file"))

        ups = UninstallPathSet(dist=Mock())
        ups.add(path1)
        ups.add(path2)
        assert ups._paths == {path1}


class TestStashedUninstallPathSet:
    WALK_RESULT: list[tuple[str, list[str], list[str]]] = [
        ("A", ["B", "C"], ["a.py"]),
        ("A/B", ["D"], ["b.py"]),
        ("A/B/D", [], ["c.py"]),
        ("A/C", [], ["d.py", "e.py"]),
        ("A/E", ["F"], ["f.py"]),
        ("A/E/F", [], []),
        ("A/G", ["H"], ["g.py"]),
        ("A/G/H", [], ["h.py"]),
    ]

    @classmethod
    def mock_walk(cls, root: str) -> Iterator[tuple[str, list[str], list[str]]]:
        for dirname, subdirs, files in cls.WALK_RESULT:
            dirname = os.path.sep.join(dirname.split("/"))
            if dirname.startswith(root):
                yield dirname[len(root) + 1 :], subdirs, files

    def test_compress_for_rename(self, monkeypatch: pytest.MonkeyPatch) -> None:
        paths = [
            os.path.sep.join(p.split("/"))
            for p in [
                "A/B/b.py",
                "A/B/D/c.py",
                "A/C/d.py",
                "A/E/f.py",
                "A/G/g.py",
            ]
        ]

        expected_paths = [
            os.path.sep.join(p.split("/"))
            for p in [
                "A/B/",  # selected everything below A/B
                "A/C/d.py",  # did not select everything below A/C
                "A/E/",  # only empty folders remain under A/E
                "A/G/g.py",  # non-empty folder remains under A/G
            ]
        ]

        monkeypatch.setattr("os.walk", self.mock_walk)

        actual_paths = compress_for_rename(paths)
        assert set(expected_paths) == set(actual_paths)

    @classmethod
    def make_stash(
        cls, tmpdir: Path, paths: list[str]
    ) -> tuple[StashedUninstallPathSet, list[tuple[str, str]]]:
        for dirname, subdirs, files in cls.WALK_RESULT:
            root = os.path.join(tmpdir, *dirname.split("/"))
            if not os.path.exists(root):
                os.mkdir(root)
            for d in subdirs:
                os.mkdir(os.path.join(root, d))
            for f in files:
                with open(os.path.join(root, f), "wb"):
                    pass

        pathset = StashedUninstallPathSet()

        paths = [os.path.join(tmpdir, *p.split("/")) for p in paths]
        stashed_paths = [(p, pathset.stash(p)) for p in paths]

        return pathset, stashed_paths

    def test_stash(self, tmpdir: Path) -> None:
        pathset, stashed_paths = self.make_stash(
            tmpdir,
            [
                "A/B/",
                "A/C/d.py",
                "A/E/",
                "A/G/g.py",
            ],
        )

        for old_path, new_path in stashed_paths:
            assert not os.path.exists(old_path)
            assert os.path.exists(new_path)

        assert stashed_paths == pathset._moves

    def test_commit(self, tmpdir: Path) -> None:
        pathset, stashed_paths = self.make_stash(
            tmpdir,
            [
                "A/B/",
                "A/C/d.py",
                "A/E/",
                "A/G/g.py",
            ],
        )

        pathset.commit()

        for old_path, new_path in stashed_paths:
            assert not os.path.exists(old_path)
            assert not os.path.exists(new_path)

    def test_rollback(self, tmpdir: Path) -> None:
        pathset, stashed_paths = self.make_stash(
            tmpdir,
            [
                "A/B/",
                "A/C/d.py",
                "A/E/",
                "A/G/g.py",
            ],
        )

        pathset.rollback()

        for old_path, new_path in stashed_paths:
            assert os.path.exists(old_path)
            assert not os.path.exists(new_path)

    @pytest.mark.skipif("sys.platform == 'win32'")
    def test_commit_symlinks(self, tmpdir: Path) -> None:
        adir = tmpdir / "dir"
        adir.mkdir()
        dirlink = tmpdir / "dirlink"
        dirlink.symlink_to(adir)
        afile = tmpdir / "file"
        afile.write_text("...")
        filelink = tmpdir / "filelink"
        filelink.symlink_to(afile)

        pathset = StashedUninstallPathSet()
        stashed_paths = []
        stashed_paths.append(pathset.stash(os.fspath(dirlink)))
        stashed_paths.append(pathset.stash(os.fspath(filelink)))
        for stashed_path in stashed_paths:
            assert os.path.lexists(stashed_path)
        assert not os.path.exists(dirlink)
        assert not os.path.exists(filelink)

        pathset.commit()

        # stash removed, links removed
        for stashed_path in stashed_paths:
            assert not os.path.lexists(stashed_path)
        assert not os.path.lexists(dirlink)
        assert not os.path.isdir(dirlink)
        assert not os.path.lexists(filelink)
        assert not os.path.isfile(filelink)

        # link targets untouched
        assert os.path.isdir(adir)
        assert os.path.isfile(afile)

    @pytest.mark.skipif("sys.platform == 'win32'")
    def test_rollback_symlinks(self, tmpdir: Path) -> None:
        adir = tmpdir / "dir"
        adir.mkdir()
        dirlink = tmpdir / "dirlink"
        dirlink.symlink_to(adir)
        afile = tmpdir / "file"
        afile.write_text("...")
        filelink = tmpdir / "filelink"
        filelink.symlink_to(afile)

        pathset = StashedUninstallPathSet()
        stashed_paths = []
        stashed_paths.append(pathset.stash(os.fspath(dirlink)))
        stashed_paths.append(pathset.stash(os.fspath(filelink)))
        for stashed_path in stashed_paths:
            assert os.path.lexists(stashed_path)
        assert not os.path.lexists(dirlink)
        assert not os.path.lexists(filelink)

        pathset.rollback()

        # stash removed, links restored
        for stashed_path in stashed_paths:
            assert not os.path.lexists(stashed_path)
        assert os.path.lexists(dirlink)
        assert os.path.isdir(dirlink)
        assert os.path.lexists(filelink)
        assert os.path.isfile(filelink)

        # link targets untouched
        assert os.path.isdir(adir)
        assert os.path.isfile(afile)


class TestPathCompactor:
    def run_compactor_pipeline(
        self,
        tmp_path: Path,
        record_paths: list[str],
        all_disk_paths: list[str],
        preserved_roots: Iterable[str] | None = None,
        populate_pycache: bool = False,
    ) -> PathCompactor:

        if populate_pycache:
            # Populate pyc of multiple optimization levels on disk
            pycache_dirs = set()
            for p in filter(lambda x: x.endswith(".py"), record_paths.copy()):
                for level in (None, 1, 2):
                    result = cache_from_source(p, optimization=level)
                    all_disk_paths.append(result)
                    record_paths.append(result)
                    pycache_dirs.add(os.path.dirname(result))

            # Add the __pycache__ directory entries to the RECORD
            record_paths.extend(d for d in pycache_dirs)

        for p in all_disk_paths:
            full_path = tmp_path / p
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.touch()

        abs_paths = [str(tmp_path / p) for p in record_paths]

        abs_preserved = None
        if preserved_roots:
            abs_preserved = [str(tmp_path / r) for r in preserved_roots]

        # Run the path pipeline for result interpretation
        compactor = PathCompactor(paths=abs_paths, preserved_roots=abs_preserved)
        compactor._parse_paths()
        compactor._calculate_roots_and_owned_paths()
        compactor._process_roots()

        return compactor

    @pytest.mark.parametrize("poison", [False, True])
    @pytest.mark.parametrize("preserve_root", [False, True])
    @pytest.mark.parametrize("pycache", [False, True])
    def test_simple_package(
        self,
        tmpdir: Path,
        poison: bool,
        preserve_root: bool,
        pycache: bool,
    ) -> None:

        poisoned_remains = [
            "lib/my_pkg/__init__.py",
            "lib/my_pkg/core.py",
        ]

        record_paths = poisoned_remains + [
            "lib/my_pkg/utils/math.py",
            "lib/my_pkg.dist-info/METADATA",
            "lib/my_pkg.dist-info/PKG-INFO",
        ]

        all_disk_paths = record_paths.copy()

        if poison:
            all_disk_paths.append("lib/my_pkg/poison.txt")

        compactor = self.run_compactor_pipeline(
            tmp_path=tmpdir,
            record_paths=record_paths,
            all_disk_paths=all_disk_paths,
            preserved_roots=[str(tmpdir / "lib")] if preserve_root else None,
            populate_pycache=pycache,
        )

        rename_set = compactor.compress_for_rename()

        expected_files = set()
        expected_wildcards = {os.path.join(str(tmpdir / "lib/my_pkg.dist-info"), "")}
        if not poison:
            # The entire package should collapse
            expected_wildcards.add(os.path.join(str(tmpdir / "lib/my_pkg"), ""))
        else:
            # When pycache is flagged, the base package will not collapse but the
            # utils package will, so there will be two wildcards: pycache in the main
            # package directory and utils as the parent of the other pycache
            expected_wildcards.add(os.path.join(str(tmpdir / "lib/my_pkg/utils"), ""))
            if pycache:
                expected_wildcards.add(
                    os.path.join(str(tmpdir / "lib/my_pkg/__pycache__"), "")
                )

            expected_files.update({str(tmpdir / p) for p in poisoned_remains})

        assert (expected_files | expected_wildcards) == rename_set

        will_remove, skipped_files = compactor.compress_for_output_listing()

        expected_remove = {
            os.path.join(str(tmpdir / "lib/my_pkg"), "") + "*",
            os.path.join(str(tmpdir / "lib/my_pkg.dist-info"), "") + "*",
        }

        # The output listing will always say that the full package is being removed
        assert compact(will_remove) == expected_remove

        expected_skip = set()

        if poison:
            expected_skip.add(str(tmpdir / "lib/my_pkg/poison.txt"))

        assert skipped_files == expected_skip

    @pytest.mark.parametrize("poison", [False, True])
    @pytest.mark.parametrize("preserve_root", [False, True])
    @pytest.mark.parametrize("pycache", [False, True])
    @pytest.mark.parametrize("pep420", [False, True])
    def test_namespace_package(
        self,
        tmpdir: Path,
        poison: bool,
        preserve_root: bool,
        pycache: bool,
        pep420: bool,
    ) -> None:
        record_paths = [
            "lib/my_pkg/core/__init__.py",
            "lib/my_pkg/core/module.py",
            "lib/my_pkg/core/ext/extension.pyi",
            "lib/my_pkg/core/ext/extension.so",
            "lib/my_pkg_core.dist-info/METADATA",
            "lib/my_pkg_core.dist-info/PKG-INFO",
        ]

        if not pep420:
            record_paths.append("lib/my_pkg/__init__.py")

        all_disk_paths = record_paths.copy()

        if poison:
            all_disk_paths.append("lib/my_pkg/pkg_b/other.py")

        compactor = self.run_compactor_pipeline(
            tmp_path=tmpdir,
            record_paths=record_paths,
            all_disk_paths=all_disk_paths,
            preserved_roots=[str(tmpdir / "lib")] if preserve_root else None,
            populate_pycache=pycache,
        )

        rename_set = compactor.compress_for_rename()

        expected_files = set()
        expected_wildcards = {
            os.path.join(str(tmpdir / "lib/my_pkg_core.dist-info"), "")
        }

        # Our results vary wildly based on that information we're provided
        if not poison:
            if preserve_root or (not pep420):
                # all paths from the preserved root are removed. In legacy namespace
                # packages, the __init__.py file allows removing the parent directory.
                expected_wildcards.add(os.path.join(str(tmpdir / "lib/my_pkg"), ""))
            else:
                # We don't have root information so can only ascend up one level
                expected_wildcards.add(
                    os.path.join(str(tmpdir / "lib/my_pkg/core"), "")
                )
        else:
            # We poison with a module under the same namespace to prevent collapsing
            expected_wildcards.add(os.path.join(str(tmpdir / "lib/my_pkg/core"), ""))
            if not pep420:
                expected_files.add(str(tmpdir / "lib/my_pkg/__init__.py"))
                if pycache:
                    expected_wildcards.add(
                        os.path.join(str(tmpdir / "lib/my_pkg/__pycache__"), "")
                    )

        assert (expected_files | expected_wildcards) == rename_set

        will_remove, skipped_files = compactor.compress_for_output_listing()

        expected_remove = {
            os.path.join(str(tmpdir / "lib/my_pkg_core.dist-info"), "") + "*"
        }

        if pep420:
            expected_remove.add(os.path.join(str(tmpdir / "lib/my_pkg/core"), "") + "*")
        else:
            expected_remove.add(os.path.join(str(tmpdir / "lib/my_pkg"), "") + "*")

        assert compact(will_remove) == expected_remove

        expected_skip = set()

        # when roots aren't preserved or it's a PEP420 namespace, we only recurse
        # up one parent, so we do not catch the fact there is a sibling package.
        # The behavior here is subject to the caveats in `compress_for_output_listing`
        if poison and not pep420:
            expected_skip.add(os.path.join(str(tmpdir / "lib/my_pkg/pkg_b"), "") + "*")

        assert skipped_files == expected_skip

    @pytest.mark.parametrize("poison", [False, True])
    @pytest.mark.parametrize("preserve_root", [False, True])
    @pytest.mark.parametrize("pycache", [False, True])
    def test_purelib_root_file(
        self,
        tmpdir: Path,
        poison: bool,
        preserve_root: bool,
        pycache: bool,
    ) -> None:
        # Note this behavior will be similar for things in bin/ or similar except
        # that bin/ will usually be poisoned by other binaries (like python)

        record_paths = [
            "lib/six.py",
            "lib/six.dist-info/METADATA",
            "lib/six.dist-info/PKG-INFO",
        ]

        all_disk_paths = record_paths.copy()

        if poison:
            all_disk_paths.append("lib/numpy/__init__.py")
            all_disk_paths.append("lib/black/__init__.py")

        compactor = self.run_compactor_pipeline(
            tmp_path=tmpdir,
            record_paths=record_paths,
            all_disk_paths=all_disk_paths,
            preserved_roots=[str(tmpdir / "lib")] if preserve_root else None,
            populate_pycache=pycache,
        )

        rename_set = compactor.compress_for_rename()

        expected_files = set()
        expected_wildcards = set()

        # If there's nothing to stop it, it will try to collapse the top directory
        # this is existing behavior, so is not new.
        if not poison and not preserve_root:
            expected_wildcards.add(os.path.join(str(tmpdir / "lib"), ""))
        else:
            expected_files.add(str(tmpdir / "lib/six.py"))
            expected_wildcards.add(os.path.join(str(tmpdir / "lib/six.dist-info"), ""))
            if pycache:
                expected_wildcards.add(
                    os.path.join(str(tmpdir / "lib/__pycache__"), "")
                )

        assert (expected_files | expected_wildcards) == rename_set

        will_remove, skipped_files = compactor.compress_for_output_listing()

        expected_remove = set()

        # Without a root to avoid globbing everything, purelib becomes a wildcard
        if not preserve_root:
            expected_remove.add(os.path.join(str(tmpdir / "lib"), "") + "*")
        else:
            expected_remove.add(str(tmpdir / "lib/six.py"))
            expected_remove.add(
                os.path.join(str(tmpdir / "lib/six.dist-info"), "") + "*"
            )
            if pycache:
                expected_remove.add(
                    os.path.join(str(tmpdir / "lib/__pycache__"), "") + "*"
                )

        assert compact(will_remove) == expected_remove

        expected_skip = set()

        if poison and not preserve_root:
            expected_skip.add(os.path.join(str(tmpdir / "lib/numpy"), "") + "*")
            expected_skip.add(os.path.join(str(tmpdir / "lib/black"), "") + "*")

        assert skipped_files == expected_skip
