[pytest]
testpaths = benchmarks
python_files = bench_*.py
pythonpath = ../src ..
addopts = --disable-socket --strict-markers --benchmark-storage=benchmarks/.benchmarks
markers =
    benchmark: performance workloads
