name: PR Checklist

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  check-pr-template:
    if: >
      !contains(github.event.pull_request.labels.*.name, 'skip PR template check')
    name: Check PR template
    runs-on: ubuntu-slim
    permissions: {}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check PR body
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_USER_LOGIN: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: bash .github/scripts/check_pr_template.sh
