name: CI

on:
  push:
    branches: [main]
    tags:
      # Tags for all potential release numbers till 2030.
      - "2[0-9].[0-3]" # 20.0 -> 29.3
      - "2[0-9].[0-3].[0-9]+" # 20.0.0 -> 29.3.[0-9]+
  pull_request:
  schedule:
    - cron: 0 0 * * MON # Run every Monday at 00:00 UTC
  workflow_dispatch:
    # allow manual runs on branches without a PR

env:
  # The "FORCE_COLOR" variable, when set to 1,
  # tells Nox to colorize itself.
  FORCE_COLOR: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tests-unix:
    name: tests / ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        python:
          - "3.13"

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - run: pip install nox

      # Main check
      - name: Run PEP 668 tests
        run: >-
          nox -s test-${{ matrix.python }} --
          tests/functional/test_pep668.py
          -xvs
