name: Check

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  check-news-entry:
    name: news entry
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          # `towncrier check` runs `git diff --name-only origin/main...`, which
          # needs a non-shallow clone.
          fetch-depth: 0

      - name: Check news entry
        if: "!contains(github.event.pull_request.labels.*.name, 'trivial')"
        run: |
          if ! pipx run towncrier check --compare-with origin/${{ github.base_ref }}; then
            echo "Please see https://pip.pypa.io/dev/news-entry-failure for guidance."
            false
          fi
