name: Update documentation redirects

on:
  push:
    branches: [main]
    paths:
      - ".readthedocs-custom-redirects.yml"
      - ".readthedocs.yml"
  schedule:
    - cron: 0 0 * * MON # Run every Monday at 00:00 UTC

env:
  FORCE_COLOR: "1"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  update-rtd-redirects:
    runs-on: ubuntu-latest
    environment: RTD Deploys
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.11"
      - run: pipx run tools/update-rtd-redirects.py
        env:
          RTD_API_TOKEN: ${{ secrets.RTD_API_TOKEN }}
